### ISSUE TITLE
Extra line causing lambda to exit.

### ISSUE THREAD

**Issue by oldmangreg** [PacktPublishing/Data-Engineering-with-AWS#1]
Hi,
Could you check to see if this line is necessary - I found the lambda function would exit on this call without making much of a fuss.  I even wrapped the code in a try/except block but this call never triggered the exception.  When I removed the line the lambda completed as expected (or at least it put a file into the clean zone bucket. 

https://github.com/PacktPublishing/Data-Engineering-with-AWS/blob/9f77a3f1ee983a0fd5ab89f493c4d457c3fe3494/Chapter03/CSVtoParquetLambda.py#L32

Thanks,
@oldmangreg

**Comment by oldmangreg** [comment]
Also getting this error `/var/task/CSVtoParquetLambda.py:54: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison`

from 
`if db_name not in current_databases.values:`

And it seems 
`wr.catalog.create_database(db_name)`
also causes the lambda to end prematurely

**Comment by oldmangreg** [comment]
This line too seems to cause the lambda to exit 
`result = wr.s3.to_parquet(
            df=input_df, 
            path=output_path, 
            dataset=True,
            database=db_name,
            table=table_name,
            mode="append")
            `

**Comment by eagarg** [comment]
Thanks for reporting the issue that you're experiencing - I'd be happy to help you troubleshoot this a bit. 

I just re-tested this code by re-doing the exercises in Chapter 3 in a new account, and I was able to get the SNAPPY file written to the target bucket using the Github code without any modifications. That said, I think line 32 is more of a debugging line and should not be necessary (since on Line 31 we're capturing the output of wr.catalog.databases() in a variable called current_databases). However having Line 32 in does not cause any problems for me.

Re the warning about 'elementwise comparison failed', this happens for me as well and I looked into it when writing the exercises for this chapter and it is just a warning about a change in Python that may affect this code if run with future Python versions, but it should not cause any issues with Python 3.8 (besides the warning coming up). 

I was also unable to reproduce the issue with the `result = wr.s3.to_parquet` line, as this code executed fine for me and did write out the SNAPPY file as expected in my target bucket. 

Can you confirm that you are running this code with the Lambda configured for Python 3.8? Also please confirm that you are using Data Wrangler version 2.10 for Python 3.8 (download link is https://github.com/awslabs/aws-data-wrangler/releases/download/2.10.0/awswrangler-layer-2.10.0-py3.8.zip). 

Thanks,

Gareth

**Comment by oldmangreg** [comment]
Hi Gareth,
Thanks for looking into this.  If your able to make it work it does seem like an issue in my environment.  I found it odd that there were no exceptions though, the lambda just ended, no exceptions, no permissions issues.  I will rebuild my environment in hopes that I had something wrong and give it another try.
Thanks again,
Greg

**Comment by oldmangreg** [comment]
Hi Gareth,
Missed the step about increasing the time out from 3s to 60s, this resolved the issue.  
Thanks again for your time!
Greg

**Comment by eagarg** [comment]
Hey Greg. Glad that you figured out what the missed step was. I know that it's easy to miss a step when working through an exercise, and you pointing this out may help others working on this exercise, so I appreciate you highlighting this. All the best. Gareth.
